require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'spec/dummy/**/*'

Style/Documentation:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false
