default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: 5432
  pool: 5

development:
  <<: *default
  database: rakeman_engine_development

test:
  <<: *default
  database: rakeman_engine_test

production:
  <<: *default
  database: rakeman_engine_production
