default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: rakeman_engine_development

test:
  <<: *default
  database: rakeman_engine_test

production:
  <<: *default
  database: rakeman_engine_production
